name: build_wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v12
      
      
    - name: Build
      # Build your program with the given configuration
      run: |
        #export CC=${{env.EMSDK}}/upstream/bin/emcc
        #export CXX=${{env.EMSDK}}/upstream/bin/em++
        #emcmake cmake -B build 
        mkdir build
        cd build
        emcmake cmake .. -DUSE_CUDA=ON -DCMAKE_CXX_COMPILER=${{env.EMSDK}}/upstream/bin/em++ -DCMAKE_C_COMPILER=${{env.EMSDK}}/upstream/bin/emcc
        emmake make -j
    - uses: actions/upload-artifact@v3
      with:
          name: build-${{ runner.os }}
          path: ./build/
