name: build_wasm

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

 
      
    - name: Build
      # Build your program with the given configuration
      run: |
        mkdir build
        cd build
        cmake .. -DUSE_CUDA=OFF
        make -j
    - uses: actions/upload-artifact@v3
      with:
          name: build-${{ runner.os }}
          path: ./build/
